name: Catkin CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.5.1
      with:
        required-ros-distributions: "melodic noetic"  # Install Melodic and Noetic ROS distributions
        install-connext: true  # Install RTI Connext

    - name: Change directory to repository
      run: cd ros_ws/gazebo_ws

    - name: Build packages
      run: catkin_make

    - name: Run tests
      run: catkin_make run_tests

    - name: Install built packages
      run: catkin_make install
